- name: Deploy Docker Container from Image (RHEL-based)
  hosts: all
  become: yes

  tasks:
    - name: Install required dependencies
      yum:
        name: yum-utils
        state: present
      when: ansible_host != "34.30.219.230"
      
      


    - name: Add Docker repository
      shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        
      when: ansible_host != "34.30.219.230"

    - name: Install Docker
      yum:
        name: docker-ce
        state: present
      when: ansible_host != "34.30.219.230"

    - name: Start and Enable Docker Service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_host != "34.30.219.230"

    - name: Pull Docker Image from Docker Hub
      command: docker pull saiteja562/jenkinsmvndocker:{{ build_number }}
      when: ansible_host != "34.30.219.230"

    - name: Stop and Remove Existing Container (if running)
      command: docker rm -f ansible_container
      ignore_errors: yes
      when: ansible_host != "34.30.219.230"

    - name: Run Docker Container
      command: docker run -d -p 8087:8081 --name ansible_container saiteja562/jenkinsmvndocker:{{ build_number }}
      when: ansible_host != "34.30.219.230"
